version: '3.8'

services:
  psql-database:
    image: dannyma/psql-digicon:1.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres
    restart: always
    ports:
      - "5432:5432"

  sqlpad:
    image: sqlpad/sqlpad:5.5
    depends_on:
      - psql-database
    ports:
      - "3000:3000"
    environment:
      SQLPAD_AUTH_DISABLED: 'true'
      SQLPAD_AUTH_DISABLED_DEFAULT_ROLE: 'admin'
      SQLPAD_APP_LOG_LEVEL: debug
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_CONNECTIONS__psql__name: postgres
      SQLPAD_CONNECTIONS__psql__driver: postgres
      SQLPAD_CONNECTIONS__psql__host: psql-database
      SQLPAD_CONNECTIONS__psql__username: postgres
      SQLPAD_CONNECTIONS__psql__password: postgres
      SQLPAD_CONNECTIONS__psql__multiStatementTransactionEnabled: 'true'
      SQLPAD_CONNECTIONS__psql__idleTimeoutSeconds: 86400